### PR TITLE
Finished

### PR DESCRIPTION
**Pull request by bry-gavino**
## In this PR

Created a recipe app which displays a list of food recipes with ingredients. The food recipe information comes from an external API. There is a search-bar function that allows the user to find specific recipes.

### 🖋  What I learned

- became more familiar with the GitHub interface and the Visual Studio Code interface
- achieved a better understanding of a pull request
- learned the basics of React
- learned about functions and class components
- how to stylize/customize an app's user interface
- how to assign className, type, and certain functions to components
- how to code an interactive user interface for practical uses
- achieved an understanding of how buttons interact with other classes, functions, and values

### 🤳 Screenshots (if applicable)

I chose a different color from the tutorial and adjusted the values in the .css files to accommodate for my screen and my style preferences (I only did that for this project since it was a tutorial for React, but I intend on abiding more strictly to the directions and requests for the actual project).
Screen Shot 2020-09-24 at 7 49 56 PM
Search bar:
Screen Shot 2020-09-24 at 7 50 23 PM
Screen Shot 2020-09-24 at 7 50 33 PM
Here's what it looks like when the screen is horizontally squeezed:
Screen Shot 2020-09-24 at 7 50 46 PM
More recipes:
Screen Shot 2020-09-24 at 7 51 21 PM

### 🐞 Questions

In line 15 of the file App.js, I have [query] instead of [search] (this was talked about in the tutorial video). I understand why [query] is preferred over [search], but I'm not exactly certain how it works. A little explanation about this would be greatly appreciated! :)

### CODE REVIEW

**Comment by micahtyong** [comment]
Hi Bryanna, great work on the recipe app! The colors and adjusted .css files look great. To answer your question, 

> I have [query] instead of [search] (this was talked about in the tutorial video). I understand why [query] is preferred over [search], but I'm not exactly certain how it works.

I like to think of _useEffect_ as an event listener. More concretely, whenever a value inside the dependencies list changes, the useEffect function "hears" this and runs whatever functions are inside. For the example you're interested in, useEffect is listening for changes to the "query" variable. 

"search" is a state variable that represents the **text that the user is currently typing**. The values for search might include "t", "to", "tof", "tofu", etc. However, we wouldn't want the query to be called for each of these phrases! That is, we want to see results for "tofu" not just results for things that contain the letter "t" or "to". 

This is why he introduces "query", another state variable that represents the **text that the user is ready to use for a query**.  It's only set when the user clicks "search", so "query" would most likely be the complete phrase that the user is searching for, like "tofu". 

He also mentions resource limits for the API. That is, we don't want to constantly call the API when typing something because we can only make 10 requests per minute. If we were searching for a recipe for "banana cream pie" but used [search] instead of [query], the API would timeout at the 10th letter and would therefore only look up "banana cre" before timing out.

**Comment by bry-gavino** [comment]
Thank you! That really clears it up for me!

**Comment by micahtyong** [comment]
Glad to hear it! Feel free to direct more of your questions to me or Cindy, your onboarding mentor (:

**Comment by cindyxzhang** [comment]
Hey Bryanna! This looks great!! :D 
Only suggestion I'd have to make it look better (it already looks great) is to maybe add some padding in the css so that your pictures and titles aren't on the very very edge of the white box. It'd make it look more centered!
Other than that, great job!!! This is super great for just learning React for the first time!!!! :D

**Comment by bry-gavino** [comment]
Thank you Cindy! I was wondering how to format it nicer like you said, so thanks for bringing that up! :D I'll definitely keep that in mind in the future!!

**Comment by cindyxzhang** [comment]
No worries! If you're interested in padding, check this out: https://www.w3schools.com/css/css_padding.asp
Also might be useful to look into the differences between margins and padding!

**Pull request merged**
